
//
// Generated by LLVM NVPTX Back-End
//

.version 5.0
.target sm_35
.address_size 64


.extern .func __kmpc_for_static_init_4_simple_generic
(
	.param .b64 __kmpc_for_static_init_4_simple_generic_param_0,
	.param .b32 __kmpc_for_static_init_4_simple_generic_param_1,
	.param .b32 __kmpc_for_static_init_4_simple_generic_param_2,
	.param .b64 __kmpc_for_static_init_4_simple_generic_param_3,
	.param .b64 __kmpc_for_static_init_4_simple_generic_param_4,
	.param .b64 __kmpc_for_static_init_4_simple_generic_param_5,
	.param .b64 __kmpc_for_static_init_4_simple_generic_param_6,
	.param .b32 __kmpc_for_static_init_4_simple_generic_param_7,
	.param .b32 __kmpc_for_static_init_4_simple_generic_param_8
)
;
.extern .func __kmpc_for_static_fini
(
	.param .b64 __kmpc_for_static_fini_param_0,
	.param .b32 __kmpc_for_static_fini_param_1
)
;
.extern .func  (.param .b64 func_retval0) __kmpc_get_data_sharing_environment_frame
(
	.param .b32 __kmpc_get_data_sharing_environment_frame_param_0,
	.param .b32 __kmpc_get_data_sharing_environment_frame_param_1
)
;
.extern .func  (.param .b64 func_retval0) __kmpc_data_sharing_environment_begin
(
	.param .b64 __kmpc_data_sharing_environment_begin_param_0,
	.param .b64 __kmpc_data_sharing_environment_begin_param_1,
	.param .b64 __kmpc_data_sharing_environment_begin_param_2,
	.param .b64 __kmpc_data_sharing_environment_begin_param_3,
	.param .b64 __kmpc_data_sharing_environment_begin_param_4,
	.param .b64 __kmpc_data_sharing_environment_begin_param_5,
	.param .b32 __kmpc_data_sharing_environment_begin_param_6
)
;
.extern .func __kmpc_kernel_prepare_parallel
(
	.param .b64 __kmpc_kernel_prepare_parallel_param_0,
	.param .b32 __kmpc_kernel_prepare_parallel_param_1
)
;
.extern .func __kmpc_kernel_deinit
(
	.param .b32 __kmpc_kernel_deinit_param_0
)
;
.extern .func  (.param .b32 func_retval0) __kmpc_kernel_parallel
(
	.param .b64 __kmpc_kernel_parallel_param_0,
	.param .b32 __kmpc_kernel_parallel_param_1
)
;
.extern .func __kmpc_kernel_init
(
	.param .b32 __kmpc_kernel_init_param_0,
	.param .b32 __kmpc_kernel_init_param_1
)
;
.global .align 1 .b8 _$_str[23] = {59, 117, 110, 107, 110, 111, 119, 110, 59, 117, 110, 107, 110, 111, 119, 110, 59, 48, 59, 48, 59, 59, 0};
.global .align 8 .u64 __unnamed_1[3] = {2207613190144, 0, generic(_$_str)};
.weak .global .align 1 .b8 __omp_offloading_fc00_1a0034d_main_l102_property[12] = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

.func _$_omp_outlined_$__wrapper(
	.param .b32 _$_omp_outlined_$__wrapper_param_0,
	.param .b32 _$_omp_outlined_$__wrapper_param_1
)
{
	.local .align 4 .b8 	__local_depot0[16];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<7>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<44>;
	.reg .b64 	%rd<69>;

	mov.u64 	%SPL, __local_depot0;
	cvta.local.u64 	%SP, %SPL;
	mov.u32	%r1, %ntid.x;
	add.s32 	%r21, %r1, -1;
	and.b32  	%r22, %r21, -32;
	mov.u16 	%rs1, 0;
	{ // callseq 0
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b32	[param0+0], %r22;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	.param .b64 retval0;
	call.uni (retval0), 
	__kmpc_get_data_sharing_environment_frame, 
	(
	param0, 
	param1
	);
	ld.param.b64	%rd6, [retval0+0];
	} // callseq 0
	ld.u32 	%r2, [%rd6];
	add.s32 	%r23, %r2, -1;
	setp.gt.s32	%p1, %r23, 1;
	@%p1 bra 	LBB0_1;
	bra.uni 	LBB0_11;
LBB0_1:
	mov.u64 	%rd43, __unnamed_1;
	cvta.global.u64 	%rd1, %rd43;
	add.u64 	%rd44, %SP, 0;
	add.u64 	%rd2, %SPL, 0;
	add.u64 	%rd45, %SP, 4;
	add.u64 	%rd3, %SPL, 4;
	add.u64 	%rd46, %SP, 8;
	add.u64 	%rd4, %SPL, 8;
	add.u64 	%rd47, %SP, 12;
	add.u64 	%rd5, %SPL, 12;
	ld.u64 	%rd7, [%rd6+48];
	ld.u64 	%rd8, [%rd6+24];
	ld.u64 	%rd9, [%rd6+40];
	ld.u64 	%rd10, [%rd6+16];
	add.s32 	%r3, %r2, -2;
	add.s32 	%r24, %r2, -3;
	mov.u32 	%r25, 0;
	st.local.u32 	[%rd2], %r25;
	st.local.u32 	[%rd3], %r24;
	mov.u32 	%r26, 1;
	st.local.u32 	[%rd4], %r26;
	st.local.u32 	[%rd5], %r25;
	add.s32 	%r27, %r1, 1023;
	and.b32  	%r28, %r27, 992;
	add.s32 	%r29, %r28, 1023;
	mov.u32	%r30, %tid.x;
	and.b32  	%r31, %r29, %r30;
	add.s32 	%r32, %r1, -32;
	mov.u32	%r33, %ctaid.x;
	mad.lo.s32 	%r4, %r33, %r32, %r31;
	mov.u32 	%r34, 33;
	{ // callseq 1
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r4;
	.param .b32 param2;
	st.param.b32	[param2+0], %r34;
	.param .b64 param3;
	st.param.b64	[param3+0], %rd47;
	.param .b64 param4;
	st.param.b64	[param4+0], %rd44;
	.param .b64 param5;
	st.param.b64	[param5+0], %rd45;
	.param .b64 param6;
	st.param.b64	[param6+0], %rd46;
	.param .b32 param7;
	st.param.b32	[param7+0], %r26;
	.param .b32 param8;
	st.param.b32	[param8+0], %r26;
	call.uni 
	__kmpc_for_static_init_4_simple_generic, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8
	);
	} // callseq 1
	ld.local.u32 	%r43, [%rd2];
	setp.ge.s32	%p2, %r43, %r3;
	@%p2 bra 	LBB0_10;
	ld.u32 	%r6, [%rd6+4];
	add.s32 	%r35, %r6, -1;
	setp.gt.s32	%p3, %r35, 1;
	ld.local.s32 	%rd16, [%rd4];
	@%p3 bra 	LBB0_5;
	bra.uni 	LBB0_3;
LBB0_5:
	cvt.s64.s32	%rd15, %r43;
	mul.lo.s64 	%rd52, %rd10, %rd15;
	shl.b64 	%rd53, %rd52, 2;
	add.s64 	%rd54, %rd8, %rd53;
	add.s64 	%rd64, %rd54, 4;
	mul.lo.s64 	%rd55, %rd10, %rd16;
	shl.b64 	%rd18, %rd55, 2;
	add.s64 	%rd19, %rd8, 4;
	add.s32 	%r39, %r43, 2;
	add.s64 	%rd20, %rd7, 4;
	add.s32 	%r38, %r43, 1;
	add.s32 	%r9, %r6, -2;
	add.s64 	%rd21, %rd8, 8;
LBB0_6:
	cvt.s64.s32	%rd56, %r39;
	mul.lo.s64 	%rd57, %rd10, %rd56;
	shl.b64 	%rd58, %rd57, 2;
	add.s64 	%rd67, %rd19, %rd58;
	cvt.s64.s32	%rd59, %r38;
	mul.lo.s64 	%rd60, %rd9, %rd59;
	shl.b64 	%rd61, %rd60, 2;
	add.s64 	%rd66, %rd20, %rd61;
	mul.lo.s64 	%rd62, %rd10, %rd59;
	shl.b64 	%rd63, %rd62, 2;
	add.s64 	%rd65, %rd21, %rd63;
	mov.u32 	%r41, %r9;
	mov.u64 	%rd68, %rd64;
LBB0_7:
	ld.f32 	%f1, [%rd65];
	ld.f32 	%f2, [%rd65+-8];
	add.rn.f32 	%f3, %f1, %f2;
	ld.f32 	%f4, [%rd68];
	add.rn.f32 	%f5, %f3, %f4;
	ld.f32 	%f6, [%rd67];
	add.rn.f32 	%f7, %f5, %f6;
	mul.rn.f32 	%f8, %f7, 0f3E800000;
	st.f32 	[%rd66], %f8;
	ld.f32 	%f9, [%rd6+88];
	ld.f32 	%f10, [%rd65+-4];
	sub.rn.f32 	%f11, %f8, %f10;
	abs.f32 	%f12, %f11;
	max.f32 	%f13, %f9, %f12;
	st.f32 	[%rd6+88], %f13;
	add.s64 	%rd68, %rd68, 4;
	add.s64 	%rd67, %rd67, 4;
	add.s64 	%rd66, %rd66, 4;
	add.s32 	%r41, %r41, -1;
	add.s64 	%rd65, %rd65, 4;
	setp.ne.s32	%p5, %r41, 0;
	@%p5 bra 	LBB0_7;
	cvt.u32.u64	%r37, %rd16;
	add.s32 	%r43, %r43, %r37;
	add.s64 	%rd64, %rd64, %rd18;
	add.s32 	%r39, %r39, %r37;
	add.s32 	%r38, %r38, %r37;
	setp.lt.s32	%p6, %r43, %r3;
	@%p6 bra 	LBB0_6;
	bra.uni 	LBB0_9;
LBB0_3:
	cvt.u32.u64	%r36, %rd16;
LBB0_4:
	add.s32 	%r43, %r43, %r36;
	setp.lt.s32	%p4, %r43, %r3;
	@%p4 bra 	LBB0_4;
LBB0_9:
	st.local.u32 	[%rd2], %r43;
LBB0_10:
	{ // callseq 2
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r4;
	call.uni 
	__kmpc_for_static_fini, 
	(
	param0, 
	param1
	);
	} // callseq 2
LBB0_11:
	ret;

}
.func _$_omp_outlined_$__$_1_wrapper(
	.param .b32 _$_omp_outlined_$__$_1_wrapper_param_0,
	.param .b32 _$_omp_outlined_$__$_1_wrapper_param_1
)
{
	.local .align 4 .b8 	__local_depot1[16];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<10>;
	.reg .b16 	%rs<2>;
	.reg .b32 	%r<55>;
	.reg .b64 	%rd<62>;

	mov.u64 	%SPL, __local_depot1;
	cvta.local.u64 	%SP, %SPL;
	mov.u32	%r1, %ntid.x;
	add.s32 	%r26, %r1, -1;
	and.b32  	%r27, %r26, -32;
	mov.u16 	%rs1, 0;
	{ // callseq 3
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b32	[param0+0], %r27;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	.param .b64 retval0;
	call.uni (retval0), 
	__kmpc_get_data_sharing_environment_frame, 
	(
	param0, 
	param1
	);
	ld.param.b64	%rd6, [retval0+0];
	} // callseq 3
	ld.u32 	%r2, [%rd6];
	add.s32 	%r28, %r2, -1;
	setp.gt.s32	%p1, %r28, 1;
	@%p1 bra 	LBB1_1;
	bra.uni 	LBB1_15;
LBB1_1:
	mov.u64 	%rd41, __unnamed_1;
	cvta.global.u64 	%rd1, %rd41;
	add.u64 	%rd42, %SP, 0;
	add.u64 	%rd2, %SPL, 0;
	add.u64 	%rd43, %SP, 4;
	add.u64 	%rd3, %SPL, 4;
	add.u64 	%rd44, %SP, 8;
	add.u64 	%rd4, %SPL, 8;
	add.u64 	%rd45, %SP, 12;
	add.u64 	%rd5, %SPL, 12;
	ld.u64 	%rd7, [%rd6+24];
	ld.u64 	%rd8, [%rd6+48];
	ld.u64 	%rd9, [%rd6+16];
	ld.u64 	%rd10, [%rd6+40];
	add.s32 	%r3, %r2, -2;
	add.s32 	%r29, %r2, -3;
	mov.u32 	%r30, 0;
	st.local.u32 	[%rd2], %r30;
	st.local.u32 	[%rd3], %r29;
	mov.u32 	%r31, 1;
	st.local.u32 	[%rd4], %r31;
	st.local.u32 	[%rd5], %r30;
	add.s32 	%r32, %r1, 1023;
	and.b32  	%r33, %r32, 992;
	add.s32 	%r34, %r33, 1023;
	mov.u32	%r35, %tid.x;
	and.b32  	%r36, %r34, %r35;
	add.s32 	%r37, %r1, -32;
	mov.u32	%r38, %ctaid.x;
	mad.lo.s32 	%r4, %r38, %r37, %r36;
	mov.u32 	%r39, 33;
	{ // callseq 4
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r4;
	.param .b32 param2;
	st.param.b32	[param2+0], %r39;
	.param .b64 param3;
	st.param.b64	[param3+0], %rd45;
	.param .b64 param4;
	st.param.b64	[param4+0], %rd42;
	.param .b64 param5;
	st.param.b64	[param5+0], %rd43;
	.param .b64 param6;
	st.param.b64	[param6+0], %rd44;
	.param .b32 param7;
	st.param.b32	[param7+0], %r31;
	.param .b32 param8;
	st.param.b32	[param8+0], %r31;
	call.uni 
	__kmpc_for_static_init_4_simple_generic, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8
	);
	} // callseq 4
	ld.local.u32 	%r54, [%rd2];
	setp.ge.s32	%p2, %r54, %r3;
	@%p2 bra 	LBB1_14;
	ld.u32 	%r6, [%rd6+4];
	add.s32 	%r7, %r6, -1;
	setp.gt.s32	%p3, %r7, 1;
	ld.local.u32 	%r8, [%rd4];
	@%p3 bra 	LBB1_3;
	bra.uni 	LBB1_12;
LBB1_3:
	add.s32 	%r40, %r6, 2;
	add.s32 	%r9, %r6, -3;
	and.b32  	%r10, %r40, 3;
	add.s64 	%rd15, %rd7, 4;
	add.s32 	%r48, %r54, 1;
	add.s64 	%rd16, %rd8, 4;
	add.s64 	%rd17, %rd8, 8;
	add.s64 	%rd18, %rd7, 8;
	setp.eq.s32	%p5, %r10, 0;
	setp.lt.u32	%p7, %r9, 3;
LBB1_4:
	cvt.s64.s32	%rd50, %r48;
	mul.lo.s64 	%rd19, %rd10, %rd50;
	mul.lo.s64 	%rd20, %rd9, %rd50;
	mov.u32 	%r51, %r31;
	@%p5 bra 	LBB1_8;
	shl.b64 	%rd51, %rd20, 2;
	add.s64 	%rd59, %rd15, %rd51;
	shl.b64 	%rd52, %rd19, 2;
	add.s64 	%rd58, %rd16, %rd52;
	mov.u32 	%r50, %r30;
LBB1_6:
	.pragma "nounroll";
	ld.u32 	%r43, [%rd58];
	st.u32 	[%rd59], %r43;
	add.s32 	%r50, %r50, 1;
	add.s64 	%rd59, %rd59, 4;
	add.s64 	%rd58, %rd58, 4;
	setp.ne.s32	%p6, %r10, %r50;
	@%p6 bra 	LBB1_6;
	add.s32 	%r51, %r10, 1;
LBB1_8:
	@%p7 bra 	LBB1_11;
	sub.s32 	%r52, %r7, %r51;
	cvt.s64.s32	%rd53, %r51;
	add.s64 	%rd54, %rd19, %rd53;
	shl.b64 	%rd55, %rd54, 2;
	add.s64 	%rd61, %rd17, %rd55;
	add.s64 	%rd56, %rd20, %rd53;
	shl.b64 	%rd57, %rd56, 2;
	add.s64 	%rd60, %rd18, %rd57;
LBB1_10:
	ld.u32 	%r44, [%rd61+-8];
	st.u32 	[%rd60+-8], %r44;
	ld.u32 	%r45, [%rd61+-4];
	st.u32 	[%rd60+-4], %r45;
	ld.u32 	%r46, [%rd61];
	st.u32 	[%rd60], %r46;
	ld.u32 	%r47, [%rd61+4];
	st.u32 	[%rd60+4], %r47;
	add.s32 	%r52, %r52, -4;
	add.s64 	%rd61, %rd61, 16;
	add.s64 	%rd60, %rd60, 16;
	setp.ne.s32	%p8, %r52, 0;
	@%p8 bra 	LBB1_10;
LBB1_11:
	add.s32 	%r54, %r54, %r8;
	add.s32 	%r48, %r48, %r8;
	setp.lt.s32	%p9, %r54, %r3;
	@%p9 bra 	LBB1_4;
	bra.uni 	LBB1_13;
LBB1_12:
	add.s32 	%r54, %r54, %r8;
	setp.lt.s32	%p4, %r54, %r3;
	@%p4 bra 	LBB1_12;
LBB1_13:
	st.local.u32 	[%rd2], %r54;
LBB1_14:
	{ // callseq 5
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r4;
	call.uni 
	__kmpc_for_static_fini, 
	(
	param0, 
	param1
	);
	} // callseq 5
LBB1_15:
	ret;

}
	// .weak	__omp_offloading_fc00_1a0034d_main_l102
.weak .entry __omp_offloading_fc00_1a0034d_main_l102(
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_0,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_1,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_2,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_3,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_4,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_5,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_6,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_7,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_8,
	.param .u64 __omp_offloading_fc00_1a0034d_main_l102_param_9
)
{
	.local .align 8 .b8 	__local_depot2[32];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<6>;
	.reg .f32 	%f<14>;
	.reg .b32 	%r<94>;
	.reg .b64 	%rd<122>;

	mov.u64 	%SPL, __local_depot2;
	cvta.local.u64 	%SP, %SPL;
	ld.param.u64 	%rd64, [__omp_offloading_fc00_1a0034d_main_l102_param_7];
	ld.param.u64 	%rd63, [__omp_offloading_fc00_1a0034d_main_l102_param_6];
	ld.param.u64 	%rd62, [__omp_offloading_fc00_1a0034d_main_l102_param_5];
	ld.param.u64 	%rd61, [__omp_offloading_fc00_1a0034d_main_l102_param_4];
	ld.param.u64 	%rd60, [__omp_offloading_fc00_1a0034d_main_l102_param_3];
	ld.param.u64 	%rd59, [__omp_offloading_fc00_1a0034d_main_l102_param_2];
	ld.param.u32 	%r1, [__omp_offloading_fc00_1a0034d_main_l102_param_0];
	ld.param.u32 	%r2, [__omp_offloading_fc00_1a0034d_main_l102_param_1];
	add.u64 	%rd66, %SP, 16;
	add.u64 	%rd67, %SP, 24;
	add.u64 	%rd68, %SP, 0;
	ld.param.u32 	%r3, [__omp_offloading_fc00_1a0034d_main_l102_param_8];
	mov.u32	%r4, %ntid.x;
	add.s32 	%r5, %r4, -32;
	mov.u16 	%rs1, 0;
	{ // callseq 6
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b32	[param0+0], %r5;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	call.uni 
	__kmpc_kernel_init, 
	(
	param0, 
	param1
	);
	} // callseq 6
	add.s32 	%r52, %r4, -1;
	and.b32  	%r6, %r52, -32;
	mov.u32	%r7, %tid.x;
	setp.ge.u32	%p2, %r7, %r5;
	@%p2 bra 	LBB2_32;
	mov.u64 	%rd65, __unnamed_1;
	cvta.global.u64 	%rd1, %rd65;
	cvta.to.local.u64 	%rd2, %rd66;
	cvta.to.local.u64 	%rd3, %rd67;
	cvta.to.local.u64 	%rd4, %rd68;
	add.u64 	%rd69, %SP, 4;
	add.u64 	%rd5, %SPL, 4;
	add.s32 	%r53, %r4, 1023;
	and.b32  	%r54, %r53, 992;
	add.s32 	%r55, %r54, 1023;
	and.b32  	%r8, %r55, %r7;
	bra.uni 	LBB2_2;
LBB2_12:
	cvt.u32.u64	%r79, %rd17;
	add.s32 	%r86, %r86, %r79;
	setp.lt.s32	%p18, %r86, %r10;
	@%p18 bra 	LBB2_12;
LBB2_13:
	st.local.u32 	[%rd2], %r86;
LBB2_14:
	{ // callseq 13
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r11;
	call.uni 
	__kmpc_for_static_fini, 
	(
	param0, 
	param1
	);
	} // callseq 13
LBB2_31:
	bar.sync 	0;
LBB2_2:
	bar.sync 	0;
	add.u64 	%rd74, %SP, 8;
	{ // callseq 7
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd74;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	.param .b32 retval0;
	call.uni (retval0), 
	__kmpc_kernel_parallel, 
	(
	param0, 
	param1
	);
	ld.param.b32	%r56, [retval0+0];
	} // callseq 7
	ld.volatile.u64 	%rd10, [%SP+8];
	setp.eq.s64	%p3, %rd10, 0;
	@%p3 bra 	LBB2_32;
	and.b32  	%r57, %r56, 1;
	setp.eq.b32	%p1, %r57, 1;
	@!%p1 bra 	LBB2_31;
	bra.uni 	LBB2_4;
LBB2_4:
	mov.u64 	%rd75, _$_omp_outlined_$__wrapper;
	setp.ne.s64	%p4, %rd10, %rd75;
	@%p4 bra 	LBB2_15;
	bra.uni 	LBB2_5;
LBB2_15:
	mov.u64 	%rd76, _$_omp_outlined_$__$_1_wrapper;
	setp.ne.s64	%p5, %rd10, %rd76;
	@%p5 bra 	LBB2_31;
	{ // callseq 8
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b32	[param0+0], %r6;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	.param .b64 retval0;
	call.uni (retval0), 
	__kmpc_get_data_sharing_environment_frame, 
	(
	param0, 
	param1
	);
	ld.param.b64	%rd36, [retval0+0];
	} // callseq 8
	ld.u32 	%r28, [%rd36];
	add.s32 	%r58, %r28, -1;
	setp.lt.s32	%p6, %r58, 2;
	@%p6 bra 	LBB2_31;
	ld.u64 	%rd37, [%rd36+24];
	ld.u64 	%rd38, [%rd36+48];
	ld.u64 	%rd39, [%rd36+16];
	ld.u64 	%rd40, [%rd36+40];
	add.s32 	%r29, %r28, -2;
	add.s32 	%r59, %r28, -3;
	mov.u32 	%r60, 0;
	st.local.u32 	[%rd2], %r60;
	st.local.u32 	[%rd3], %r59;
	mov.u32 	%r61, 1;
	st.local.u32 	[%rd4], %r61;
	st.local.u32 	[%rd5], %r60;
	mov.u32	%r62, %ctaid.x;
	mad.lo.s32 	%r30, %r62, %r5, %r8;
	mov.u32 	%r63, 33;
	{ // callseq 9
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r30;
	.param .b32 param2;
	st.param.b32	[param2+0], %r63;
	.param .b64 param3;
	st.param.b64	[param3+0], %rd69;
	.param .b64 param4;
	st.param.b64	[param4+0], %rd66;
	.param .b64 param5;
	st.param.b64	[param5+0], %rd67;
	.param .b64 param6;
	st.param.b64	[param6+0], %rd68;
	.param .b32 param7;
	st.param.b32	[param7+0], %r61;
	.param .b32 param8;
	st.param.b32	[param8+0], %r61;
	call.uni 
	__kmpc_for_static_init_4_simple_generic, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8
	);
	} // callseq 9
	ld.local.u32 	%r93, [%rd2];
	setp.ge.s32	%p7, %r93, %r29;
	@%p7 bra 	LBB2_30;
	ld.u32 	%r32, [%rd36+4];
	add.s32 	%r33, %r32, -1;
	setp.gt.s32	%p8, %r33, 1;
	ld.local.u32 	%r34, [%rd4];
	@%p8 bra 	LBB2_19;
	bra.uni 	LBB2_28;
LBB2_19:
	add.s32 	%r64, %r32, 2;
	add.s32 	%r35, %r32, -3;
	and.b32  	%r36, %r64, 3;
	add.s64 	%rd41, %rd37, 4;
	add.s32 	%r87, %r93, 1;
	add.s64 	%rd42, %rd38, 4;
	add.s64 	%rd43, %rd38, 8;
	add.s64 	%rd44, %rd37, 8;
LBB2_20:
	setp.eq.s32	%p10, %r36, 0;
	cvt.s64.s32	%rd81, %r87;
	mul.lo.s64 	%rd45, %rd40, %rd81;
	mul.lo.s64 	%rd46, %rd39, %rd81;
	mov.u32 	%r90, %r61;
	@%p10 bra 	LBB2_24;
	shl.b64 	%rd82, %rd46, 2;
	add.s64 	%rd119, %rd41, %rd82;
	shl.b64 	%rd83, %rd45, 2;
	add.s64 	%rd118, %rd42, %rd83;
	mov.u32 	%r89, %r60;
LBB2_22:
	.pragma "nounroll";
	ld.u32 	%r67, [%rd118];
	st.u32 	[%rd119], %r67;
	add.s32 	%r89, %r89, 1;
	add.s64 	%rd119, %rd119, 4;
	add.s64 	%rd118, %rd118, 4;
	setp.ne.s32	%p11, %r36, %r89;
	@%p11 bra 	LBB2_22;
	add.s32 	%r90, %r36, 1;
LBB2_24:
	setp.lt.u32	%p12, %r35, 3;
	@%p12 bra 	LBB2_27;
	sub.s32 	%r91, %r33, %r90;
	cvt.s64.s32	%rd84, %r90;
	add.s64 	%rd85, %rd45, %rd84;
	shl.b64 	%rd86, %rd85, 2;
	add.s64 	%rd121, %rd43, %rd86;
	add.s64 	%rd87, %rd46, %rd84;
	shl.b64 	%rd88, %rd87, 2;
	add.s64 	%rd120, %rd44, %rd88;
LBB2_26:
	ld.u32 	%r68, [%rd121+-8];
	st.u32 	[%rd120+-8], %r68;
	ld.u32 	%r69, [%rd121+-4];
	st.u32 	[%rd120+-4], %r69;
	ld.u32 	%r70, [%rd121];
	st.u32 	[%rd120], %r70;
	ld.u32 	%r71, [%rd121+4];
	st.u32 	[%rd120+4], %r71;
	add.s32 	%r91, %r91, -4;
	add.s64 	%rd121, %rd121, 16;
	add.s64 	%rd120, %rd120, 16;
	setp.ne.s32	%p13, %r91, 0;
	@%p13 bra 	LBB2_26;
LBB2_27:
	add.s32 	%r93, %r93, %r34;
	add.s32 	%r87, %r87, %r34;
	setp.lt.s32	%p14, %r93, %r29;
	@%p14 bra 	LBB2_20;
	bra.uni 	LBB2_29;
LBB2_28:
	add.s32 	%r93, %r93, %r34;
	setp.lt.s32	%p9, %r93, %r29;
	@%p9 bra 	LBB2_28;
LBB2_29:
	st.local.u32 	[%rd2], %r93;
LBB2_30:
	{ // callseq 10
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r30;
	call.uni 
	__kmpc_for_static_fini, 
	(
	param0, 
	param1
	);
	} // callseq 10
	bra.uni 	LBB2_31;
LBB2_5:
	{ // callseq 11
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b32	[param0+0], %r6;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	.param .b64 retval0;
	call.uni (retval0), 
	__kmpc_get_data_sharing_environment_frame, 
	(
	param0, 
	param1
	);
	ld.param.b64	%rd11, [retval0+0];
	} // callseq 11
	ld.u32 	%r9, [%rd11];
	add.s32 	%r72, %r9, -1;
	setp.lt.s32	%p15, %r72, 2;
	@%p15 bra 	LBB2_31;
	ld.u64 	%rd12, [%rd11+48];
	ld.u64 	%rd13, [%rd11+24];
	ld.u64 	%rd14, [%rd11+40];
	ld.u64 	%rd15, [%rd11+16];
	add.s32 	%r10, %r9, -2;
	add.s32 	%r73, %r9, -3;
	mov.u32 	%r74, 0;
	st.local.u32 	[%rd2], %r74;
	st.local.u32 	[%rd3], %r73;
	mov.u32 	%r75, 1;
	st.local.u32 	[%rd4], %r75;
	st.local.u32 	[%rd5], %r74;
	mov.u32	%r76, %ctaid.x;
	mad.lo.s32 	%r11, %r76, %r5, %r8;
	mov.u32 	%r77, 33;
	{ // callseq 12
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd1;
	.param .b32 param1;
	st.param.b32	[param1+0], %r11;
	.param .b32 param2;
	st.param.b32	[param2+0], %r77;
	.param .b64 param3;
	st.param.b64	[param3+0], %rd69;
	.param .b64 param4;
	st.param.b64	[param4+0], %rd66;
	.param .b64 param5;
	st.param.b64	[param5+0], %rd67;
	.param .b64 param6;
	st.param.b64	[param6+0], %rd68;
	.param .b32 param7;
	st.param.b32	[param7+0], %r75;
	.param .b32 param8;
	st.param.b32	[param8+0], %r75;
	call.uni 
	__kmpc_for_static_init_4_simple_generic, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8
	);
	} // callseq 12
	ld.local.u32 	%r86, [%rd2];
	setp.ge.s32	%p16, %r86, %r10;
	@%p16 bra 	LBB2_14;
	ld.u32 	%r13, [%rd11+4];
	add.s32 	%r78, %r13, -1;
	setp.gt.s32	%p17, %r78, 1;
	ld.local.s32 	%rd17, [%rd4];
	@%p17 bra 	LBB2_8;
	bra.uni 	LBB2_12;
LBB2_8:
	cvt.s64.s32	%rd16, %r86;
	add.s64 	%rd18, %rd13, 4;
	mul.lo.s64 	%rd93, %rd15, %rd16;
	shl.b64 	%rd94, %rd93, 2;
	add.s64 	%rd113, %rd18, %rd94;
	mul.lo.s64 	%rd95, %rd15, %rd17;
	shl.b64 	%rd20, %rd95, 2;
	add.s32 	%r82, %r86, 2;
	add.s64 	%rd21, %rd12, 4;
	add.s32 	%r81, %r86, 1;
	add.s32 	%r16, %r13, -2;
	add.s64 	%rd22, %rd13, 8;
LBB2_9:
	cvt.s64.s32	%rd96, %r82;
	mul.lo.s64 	%rd97, %rd15, %rd96;
	shl.b64 	%rd98, %rd97, 2;
	add.s64 	%rd116, %rd18, %rd98;
	cvt.s64.s32	%rd99, %r81;
	mul.lo.s64 	%rd100, %rd14, %rd99;
	shl.b64 	%rd101, %rd100, 2;
	add.s64 	%rd115, %rd21, %rd101;
	mul.lo.s64 	%rd102, %rd15, %rd99;
	shl.b64 	%rd103, %rd102, 2;
	add.s64 	%rd114, %rd22, %rd103;
	mov.u32 	%r84, %r16;
	mov.u64 	%rd117, %rd113;
LBB2_10:
	ld.f32 	%f1, [%rd114];
	ld.f32 	%f2, [%rd114+-8];
	add.rn.f32 	%f3, %f1, %f2;
	ld.f32 	%f4, [%rd117];
	add.rn.f32 	%f5, %f3, %f4;
	ld.f32 	%f6, [%rd116];
	add.rn.f32 	%f7, %f5, %f6;
	mul.rn.f32 	%f8, %f7, 0f3E800000;
	st.f32 	[%rd115], %f8;
	ld.f32 	%f9, [%rd11+88];
	ld.f32 	%f10, [%rd114+-4];
	sub.rn.f32 	%f11, %f8, %f10;
	abs.f32 	%f12, %f11;
	max.f32 	%f13, %f9, %f12;
	st.f32 	[%rd11+88], %f13;
	add.s64 	%rd117, %rd117, 4;
	add.s64 	%rd116, %rd116, 4;
	add.s64 	%rd115, %rd115, 4;
	add.s32 	%r84, %r84, -1;
	add.s64 	%rd114, %rd114, 4;
	setp.ne.s32	%p19, %r84, 0;
	@%p19 bra 	LBB2_10;
	cvt.u32.u64	%r80, %rd17;
	add.s32 	%r86, %r86, %r80;
	add.s64 	%rd113, %rd113, %rd20;
	add.s32 	%r82, %r82, %r80;
	add.s32 	%r81, %r81, %r80;
	setp.lt.s32	%p20, %r86, %r10;
	@%p20 bra 	LBB2_9;
	bra.uni 	LBB2_13;
LBB2_32:
	setp.ne.s32	%p21, %r7, %r6;
	@%p21 bra 	LBB2_34;
	add.u64 	%rd104, %SP, 8;
	mov.u64 	%rd108, 96;
	mov.u64 	%rd109, 256;
	{ // callseq 14
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd104;
	.param .b64 param1;
	st.param.b64	[param1+0], %rd66;
	.param .b64 param2;
	st.param.b64	[param2+0], %rd67;
	.param .b64 param3;
	st.param.b64	[param3+0], %rd68;
	.param .b64 param4;
	st.param.b64	[param4+0], %rd108;
	.param .b64 param5;
	st.param.b64	[param5+0], %rd109;
	.param .b32 param6;
	st.param.b16	[param6+0], %rs1;
	.param .b64 retval0;
	call.uni (retval0), 
	__kmpc_data_sharing_environment_begin, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6
	);
	ld.param.b64	%rd110, [retval0+0];
	} // callseq 14
	st.u32 	[%rd110], %r1;
	st.u32 	[%rd110+4], %r2;
	st.u64 	[%rd110+24], %rd64;
	st.u64 	[%rd110+48], %rd61;
	st.u32 	[%rd110+88], %r3;
	st.u64 	[%rd110+8], %rd62;
	st.u64 	[%rd110+16], %rd63;
	st.u64 	[%rd110+32], %rd59;
	st.u64 	[%rd110+40], %rd60;
	st.u64 	[%rd110+56], %rd59;
	st.u64 	[%rd110+64], %rd60;
	st.u64 	[%rd110+72], %rd62;
	st.u64 	[%rd110+80], %rd63;
	mov.u64 	%rd111, _$_omp_outlined_$__wrapper;
	{ // callseq 15
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd111;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	call.uni 
	__kmpc_kernel_prepare_parallel, 
	(
	param0, 
	param1
	);
	} // callseq 15
	bar.sync 	0;
	bar.sync 	0;
	mov.u64 	%rd112, _$_omp_outlined_$__$_1_wrapper;
	{ // callseq 16
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64	[param0+0], %rd112;
	.param .b32 param1;
	st.param.b16	[param1+0], %rs1;
	call.uni 
	__kmpc_kernel_prepare_parallel, 
	(
	param0, 
	param1
	);
	} // callseq 16
	bar.sync 	0;
	bar.sync 	0;
	{ // callseq 17
	.reg .b32 temp_param_reg;
	.param .b32 param0;
	st.param.b16	[param0+0], %rs1;
	call.uni 
	__kmpc_kernel_deinit, 
	(
	param0
	);
	} // callseq 17
	bar.sync 	0;
LBB2_34:
	ret;

}

